### ISSUE TITLE
There is no license information in the mod file

### ISSUE THREAD

**Issue by Vadim122608** [JustAlittleWolf/SmoothScrollingRefurbished#5]
minecraft version 1.16.5
https://github.com/user-attachments/assets/abde0a91-ed7c-4e92-ab4b-c3503ab8cdc2

**Comment by JustAlittleWolf** [comment]
Hi, I think this is for a [different mod](https://www.curseforge.com/minecraft/mc-mods/smooth-scrolling-everywhere-fabric)? My mod does not have a 1.3 version, and does not work with 1.16.5
